# Site settings
title: Ambient Intelligence
description: > # this means to ignore newlines until "baseurl:"
  Projects realized by the students of the AmI course (Politecnico di Torino,
  Italy) in the year 2018. Theme of the projects is AmI for Living Spaces.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ami-2018.github.io" # the base hostname & protocol for your site
github_username: "AmI-2018"
facebook_group: "polito.ami"

# Build settings
markdown: kramdown
